#pragma once

#ifndef QVTK_DEFINE_H
#define QVTK_DEFINE_H

#ifndef VTK_IN_VTK
#define VTK_IN_VTK
#endif

#include "vtkAutoInit.h"   
VTK_MODULE_INIT(vtkRenderingOpenGL2); // VTK was built with vtkRenderingOpenGL2  
VTK_MODULE_INIT(vtkInteractionStyle);

//#ifndef vtkRenderingCore_INCLUDE
//#define vtkRenderingCore_INCLUDE "vtkRenderingCore_AUTOINIT_vtkInteractionStyle_vtkRenderingFreeType_vtkRenderingOpenGL2.h"
//#endif

#ifndef _x64

//#ifdef _DEBUG
////#pragma comment(lib, "G:/C++/vtkTest/lib/debug/qtmaind.lib")
////#pragma comment(lib, "../C++/vtkTest/lib/debug/QtCored4.lib")
////#pragma comment(lib, "../C++/vtkTest/lib/debug/QtGuid4.lib")
////#pragma comment(lib, "../C++/vtkTest/lib/debug/QtOpenGLd4.lib")
//#pragma comment(lib, "../lib/vtkInteractionWidgets-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersHybrid-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersModeling-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersVerdict-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkImagingGeneral-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkInteractionStyle-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkRenderingAnnotation-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkImagingColor-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkRenderingFreeType-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkfreetype-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkRenderingVolume-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkRenderingOpenGL2-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkglew-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkImagingSources-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkRenderingCore-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkRenderingLOD-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersSources-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonColor-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersExtraction-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersGeneral-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonComputationalGeometry-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersStatistics-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkImagingFourier-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkalglib-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersGeometry-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkFiltersCore-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkImagingHybrid-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkImagingCore-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkIOImage-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkDICOMParser-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkIOCore-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkIOGeometry-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonExecutionModel-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonDataModel-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonMisc-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonSystem-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtksys-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonTransforms-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonMath-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkCommonCore-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkmetaio-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkpng-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtktiff-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkzlib-7.0.lib")
//#pragma comment(lib, "../C++/vtkTest/lib/debug/vtkjpeg-7.0.lib")
//#else
//#pragma comment(lib, "../ThirdPart/QT47/lib/release/qtmain.lib")
//#pragma comment(lib, "../ThirdPart/QT47/lib/release/QtCore4.lib")
//#pragma comment(lib, "../ThirdPart/QT47/lib/release/QtGui4.lib")
//#pragma comment(lib, "../ThirdPart/QT47/lib/release/QtOpenGL4.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkInteractionWidgets-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersHybrid-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersModeling-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersVerdict-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkImagingGeneral-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkInteractionStyle-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkRenderingAnnotation-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkImagingColor-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkRenderingFreeType-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkfreetype-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkRenderingVolume-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkRenderingOpenGL2-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkglew-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkImagingSources-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkRenderingCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkRenderingLOD-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersSources-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonColor-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersExtraction-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersGeneral-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonComputationalGeometry-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersStatistics-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkImagingFourier-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkalglib-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersGeometry-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkFiltersCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkImagingHybrid-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkImagingCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkIOImage-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkDICOMParser-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkIOCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkIOGeometry-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonExecutionModel-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonDataModel-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonMisc-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonSystem-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtksys-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonTransforms-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonMath-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkCommonCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkmetaio-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkpng-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtktiff-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkzlib-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/release/vtkjpeg-7.0.lib")
//#endif
//
//#else
//
//#ifdef _DEBUG
//#pragma comment(lib, "../ThirdPart/QT47/lib/debugx64/qtmaind.lib")
//#pragma comment(lib, "../ThirdPart/QT47/lib/debugx64/QtCored4.lib")
//#pragma comment(lib, "../ThirdPart/QT47/lib/debugx64/QtGuid4.lib")
//#pragma comment(lib, "../ThirdPart/QT47/lib/debugx64/QtOpenGLd4.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkInteractionWidgets-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersHybrid-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersModeling-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersVerdict-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkImagingGeneral-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkInteractionStyle-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkRenderingAnnotation-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkImagingColor-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkRenderingFreeType-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkfreetype-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkRenderingVolume-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkRenderingOpenGL2-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkglew-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkImagingSources-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkRenderingCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkRenderingLOD-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersSources-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonColor-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersExtraction-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersGeneral-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonComputationalGeometry-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersStatistics-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkImagingFourier-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkalglib-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersGeometry-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkFiltersCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkImagingHybrid-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkImagingCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkIOImage-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkDICOMParser-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkIOCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkIOGeometry-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonExecutionModel-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonDataModel-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonMisc-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonSystem-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtksys-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonTransforms-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonMath-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkCommonCore-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkmetaio-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkpng-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtktiff-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkzlib-7.0.lib")
//#pragma comment(lib, "../ThirdPart/VTK7/lib/debugx64/vtkjpeg-7.0.lib")
//#else
// #pragma comment(lib, "../ThirdPart/QT47/lib/releasex64/qtmain.lib")
// #pragma comment(lib, "../ThirdPart/QT47/lib/releasex64/QtCore4.lib")
// #pragma comment(lib, "../ThirdPart/QT47/lib/releasex64/QtGui4.lib")
// #pragma comment(lib, "../ThirdPart/QT47/lib/releasex64/QtOpenGL4.lib")
#pragma comment(lib, "../lib/vtkInteractionWidgets-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersHybrid-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersModeling-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersVerdict-7.0.lib")
#pragma comment(lib, "../lib/vtkImagingGeneral-7.0.lib")
#pragma comment(lib, "../lib/vtkInteractionImage-7.0.lib")
#pragma comment(lib, "../lib/vtkInteractionStyle-7.0.lib")
#pragma comment(lib, "../lib/vtkRenderingAnnotation-7.0.lib")
#pragma comment(lib, "../lib/vtkImagingColor-7.0.lib")
#pragma comment(lib, "../lib/vtkRenderingFreeType-7.0.lib")
#pragma comment(lib, "../lib/vtkfreetype-7.0.lib")
#pragma comment(lib, "../lib/vtkRenderingVolume-7.0.lib")
#pragma comment(lib, "../lib/vtkRenderingOpenGL2-7.0.lib")
#pragma comment(lib, "../lib/vtkglew-7.0.lib")
#pragma comment(lib, "../lib/vtkImagingSources-7.0.lib")
#pragma comment(lib, "../lib/vtkRenderingCore-7.0.lib")
#pragma comment(lib, "../lib/vtkRenderingLOD-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersSources-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonColor-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersExtraction-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersGeneral-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonComputationalGeometry-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersStatistics-7.0.lib")
#pragma comment(lib, "../lib/vtkImagingFourier-7.0.lib")
#pragma comment(lib, "../lib/vtkalglib-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersGeometry-7.0.lib")
#pragma comment(lib, "../lib/vtkFiltersCore-7.0.lib")
#pragma comment(lib, "../lib/vtkImagingHybrid-7.0.lib")
#pragma comment(lib, "../lib/vtkImagingCore-7.0.lib")
#pragma comment(lib, "../lib/vtkIOImage-7.0.lib")
#pragma comment(lib, "../lib/vtkDICOMParser-7.0.lib")
#pragma comment(lib, "../lib/vtkIOCore-7.0.lib")
#pragma comment(lib, "../lib/vtkIOGeometry-7.0.lib")
#pragma comment(lib, "../lib/vtkIOLegacy-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonExecutionModel-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonDataModel-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonMisc-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonSystem-7.0.lib")
#pragma comment(lib, "../lib/vtksys-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonTransforms-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonMath-7.0.lib")
#pragma comment(lib, "../lib/vtkCommonCore-7.0.lib")
#pragma comment(lib, "../lib/vtkmetaio-7.0.lib")
#pragma comment(lib, "../lib/vtkpng-7.0.lib")
#pragma comment(lib, "../lib/vtktiff-7.0.lib")
#pragma comment(lib, "../lib/vtkzlib-7.0.lib")
#pragma comment(lib, "../lib/vtkjpeg-7.0.lib")
#endif

#endif

//#endif